import { Company, Member, Package, Trainer, Employee } from "../types";

export const dummyCompanies: Company[] = [
  {
    id: "c1",
    name: "Netlogg Pvt Ltd",
    email: "info@netlogg.com",
    phone: "0300-1111111",
    address: "Phase 7, Bahria Town, Islamabad",
    industry: "Software Development",
    membersLimit: 50,
    status: "active",
    joinDate: "2023-01-10",
  },
  {
    id: "c2",
    name: "10 Pearls Pvt Ltd",
    email: "hr@10pearls.com",
    phone: "0300-2222222",
    address: "Blue Area, Islamabad",
    industry: "IT Services",
    membersLimit: 100,
    status: "active",
    joinDate: "2023-03-15",
  },
  {
    id: "c3",
    name: "AppInSnap Pvt Ltd",
    email: "contact@appinsnap.com",
    phone: "0300-3333333",
    address: "Gulberg, Lahore",
    industry: "Mobile App Development",
    membersLimit: 30,
    status: "active",
    joinDate: "2023-05-20",
  },
  {
    id: "c4",
    name: "Systems Limited",
    email: "info@systemsltd.com",
    phone: "0300-4444444",
    address: "DHA Phase 6, Karachi",
    industry: "Technology",
    membersLimit: 200,
    status: "active",
    joinDate: "2022-11-05",
  },
  {
    id: "c5",
    name: "Symmetry Group",
    email: "hello@symmetrygroup.biz",
    phone: "0300-5555555",
    address: "Clifton, Karachi",
    industry: "Digital Marketing",
    membersLimit: 25,
    status: "inactive",
    joinDate: "2023-08-12",
  },
  {
    id: "c6",
    name: "Folio3",
    email: "careers@folio3.com",
    phone: "0300-6666666",
    address: "Shahrah-e-Faisal, Karachi",
    industry: "Software Engineering",
    membersLimit: 75,
    status: "active",
    joinDate: "2023-02-28",
  },
  {
    id: "c7",
    name: "Arbisoft",
    email: "info@arbisoft.com",
    phone: "0300-7777777",
    address: "Canal Bank Road, Lahore",
    industry: "Software Solutions",
    membersLimit: 150,
    status: "active",
    joinDate: "2022-09-14",
  },
  {
    id: "c8",
    name: "Devsinc",
    email: "contact@devsinc.com",
    phone: "0300-8888888",
    address: "Johar Town, Lahore",
    industry: "Tech Consulting",
    membersLimit: 120,
    status: "active",
    joinDate: "2023-06-01",
  },
];

export const dummyMembers: Member[] = [
  {
    id: "1",
    name: "Ahmed Khan",
    fatherName: "Ibrahim Khan",
    cnic: "42101-1234567-1",
    gender: "male",
    phone: "0300-1234567",
    location: "Soan Garden",
    paymentMode: "Cash",
    joinDate: "2024-01-15",
    status: "active",
    packageId: "pkg-1",
    packageName: "Monthly",
    memberType: "normal",
  },
  {
    id: "2",
    name: "Sara Ali",
    fatherName: "Ali Ahmed",
    cnic: "42101-7654321-2",
    gender: "female",
    phone: "0321-7654321",
    location: "Bahria Town",
    paymentMode: "Bank Transfer",
    joinDate: "2024-02-10",
    status: "active",
    packageId: "pkg-2",
    packageName: "Quaterly",
    memberType: "normal",
  },
  {
    id: "3",
    name: "Zainab Bibi",
    fatherName: "Muhammad Hussain",
    cnic: "42101-9876543-3",
    gender: "female",
    phone: "0311-9876543",
    location: "Soan Garden",
    paymentMode: "Easypaisa",
    joinDate: "2023-11-20",
    status: "inactive",
    packageId: "pkg-1",
    packageName: "Monthly",
    memberType: "normal",
  },
  {
    id: "4",
    name: "John Doe",
    fatherName: "Richard Doe",
    cnic: "42101-1111111-4",
    gender: "male",
    phone: "0300-1111111",
    location: "Soan Garden",
    paymentMode: "Cash",
    joinDate: "2024-01-01",
    status: "active",
    packageId: "pkg-3",
    packageName: "Six Month",
    memberType: "company",
    companyId: "c1",
    companyName: "Netlogg Pvt Ltd",
  },
  {
  id: "5",
  name: "Usman Tariq",
  fatherName: "Tariq Mehmood",
  cnic: "42101-2222222-5",
  gender: "male",
  phone: "0302-2222222",
  location: "Soan Garden",
  paymentMode: "Cash",
  joinDate: "2024-03-05",
  status: "active",
  packageId: "pkg-2",
  packageName: "Quaterly",
  memberType: "normal",
},
{
  id: "6",
  name: "Hina Shah",
  fatherName: "Shahzad Ahmed",
  cnic: "42101-3333333-6",
  gender: "female",
  phone: "0312-3333333",
location: "Soan Garden",
  paymentMode: "Cash",
  joinDate: "2023-12-15",
  status: "active",
  packageId: "pkg-3",
  packageName: "Six Month",
  memberType: "normal",
},
{
  id: "7",
  name: "Bilal Raza",
  fatherName: "Raza Ali",
  cnic: "42101-4444444-7",
  gender: "male",
  phone: "0305-4444444",
  location: "Soan Garden",
  paymentMode: "Bank Transfer",
  joinDate: "2024-01-25",
  status: "inactive",
  packageId: "pkg-1",
  packageName: "Monthly",
  memberType: "normal",
},
{
  id: "8",
  name: "Fatima Noor",
  fatherName: "Noor Ahmed",
  cnic: "42101-5555555-8",
  gender: "female",
  phone: "0333-5555555",
  location: "Soan Garden",
  paymentMode: "Easypaisa",
  joinDate: "2024-02-18",
  status: "active",
  packageId: "pkg-4",
  packageName: "Yearly",
  memberType: "normal",
},
{
  id: "9",
  name: "Hamza Siddiqui",
  fatherName: "Siddiqui Ahmed",
  cnic: "42101-6666666-9",
  gender: "male",
  phone: "0307-6666666",
  location: "Bahria Town",
  paymentMode: "Cash",
  joinDate: "2023-10-10",
  status: "inactive",
  packageId: "pkg-2",
  packageName: "Quaterly",
  memberType: "normal",
},
{
  id: "10",
  name: "Ayesha Malik",
  fatherName: "Malik Usman",
  cnic: "42101-7777777-0",
  gender: "female",
  phone: "0315-7777777",
  location: "Soan Garden",
  paymentMode: "Cash",
  joinDate: "2024-03-01",
  status: "active",
  packageId: "pkg-1",
  packageName: "Monthly",
  memberType: "company",
  companyId: "c2",
  companyName: "TechNova Solutions",
},
{
  id: "11",
  name: "Imran Qureshi",
  fatherName: "Qureshi Ahmed",
  cnic: "42101-8888888-1",
  gender: "male",
  phone: "0308-8888888",
  location: "Bahria Town",
  paymentMode: "Cash",
  joinDate: "2023-09-12",
  status: "inactive",
  packageId: "pkg-3",
  packageName: "Six Month",
  memberType: "normal",
},
{
  id: "12",
  name: "Sana Iqbal",
  fatherName: "Iqbal Hussain",
  cnic: "42101-9999999-2",
  gender: "female",
  phone: "0322-9999999",
  location: "Bahria Town",
  paymentMode: "Bank Transfer",
  joinDate: "2024-01-08",
  status: "active",
  packageId: "pkg-4",
  packageName: "Yearly",
  memberType: "normal",
},
{
  id: "13",
  name: "Ali Raza",
  fatherName: "Raza Hussain",
  cnic: "42101-1010101-3",
  gender: "male",
  phone: "0309-1010101",
  location: "Bahria Town",
  paymentMode: "Easypaisa",
  joinDate: "2024-02-22",
  status: "active",
  packageId: "pkg-2",
  packageName: "Quaterly",
  memberType: "normal",
},
{
  id: "14",
  name: "Mehwish Khan",
  fatherName: "Khan Ahmed",
  cnic: "42101-2020202-4",
  gender: "female",
  phone: "0310-2020202",
  location: "Soan Garden",
  paymentMode: "Cash",
  joinDate: "2023-11-05",
  status: "inactive",
  packageId: "pkg-1",
  packageName: "Monthly",
  memberType: "normal",
},
{
  id: "15",
  name: "Farhan Ali",
  fatherName: "Ali Raza",
  cnic: "42101-3030303-5",
  gender: "male",
  phone: "0301-3030303",
  location: "Bahria Town",
  paymentMode: "Easypaisa",
  joinDate: "2024-03-10",
  status: "active",
  packageId: "pkg-3",
  packageName: "Six Month",
  memberType: "company",
  companyId: "c1",
  companyName: "Netlogg Pvt Ltd",
},
{
  id: "16",
  name: "Rabia Hassan",
  fatherName: "Hassan Mehmood",
  cnic: "42101-4040404-6",
  gender: "female",
  phone: "0334-4040404",
  location: "Soan Garden",
  paymentMode: "Cash",
  joinDate: "2024-01-30",
  status: "active",
  packageId: "pkg-4",
  packageName: "Yearly",
  memberType: "normal",
},
{
  id: "17",
  name: "Saad Ahmed",
  fatherName: "Ahmed Raza",
  cnic: "42101-5050505-7",
  gender: "male",
  phone: "0306-5050505",
  location: "Bahria Town",
  paymentMode: "Bank Transfer",
  joinDate: "2023-12-20",
  status: "inactive",
  packageId: "pkg-2",
  packageName: "Quaterly",
  memberType: "normal",
},
{
  id: "18",
  name: "Nida Fatima",
  fatherName: "Fatima Ali",
  cnic: "42101-6060606-8",
  gender: "female",
  phone: "0316-6060606",
  location: "Soan Garden",
  paymentMode: "Easypaisa",
  joinDate: "2024-02-14",
  status: "active",
  packageId: "pkg-1",
  packageName: "Monthly",
  memberType: "normal",
},
{
  id: "19",
  name: "Kamran Yousaf",
  fatherName: "Yousaf Ahmed",
  cnic: "42101-7070707-9",
  gender: "male",
  phone: "0303-7070707",
  location: "Bahria Town",
  paymentMode: "Cash",
  joinDate: "2023-10-01",
  status: "inactive",
  packageId: "pkg-3",
  packageName: "Six Month",
  memberType: "normal",
},
{
  id: "20",
  name: "Areeba Noor",
  fatherName: "Noor Hussain",
  cnic: "42101-8080808-0",
  gender: "female",
  phone: "0320-8080808",
  location: "Soan Garden",
  paymentMode: "Cash",
  joinDate: "2024-03-12",
  status: "active",
  packageId: "pkg-4",
  packageName: "Yearly",
  memberType: "company",
  companyId: "c2",
  companyName: "TechNova Solutions",
},
];

export const dummyPackages: Package[] = [
  {
    id: "1",
    name: "Monthly",
    price: 2000,
    duration: "1 Month",
    description: "Standard monthly membership.",
    status: "active",
  },
  {
    id: "2",
    name: "Quaterly",
    price: 5000,
    duration: "3 Months",
    description: "Standard quarterly membership.",
    status: "active",
  },
  {
    id: "3",
    name: "Six Month",
    price: 9000,
    duration: "6 Months",
    description: "Standard six-month membership.",
    status: "active",
  },
  {
    id: "4",
    name: "Yearly",
    price: 15000,
    duration: "12 Months",
    description: "Standard yearly membership.",
    status: "active",
  },
  {
    id: "5",
    name: "2 Person Group",
    price: 3500,
    duration: "1 Month",
    description: "Group membership for 2 persons.",
    status: "active",
  },
  {
    id: "6",
    name: "3 Person Group",
    price: 5000,
    duration: "1 Month",
    description: "Group membership for 3 persons.",
    status: "active",
  },
  {
    id: "7",
    name: "TouchStone",
    price: 2500,
    duration: "1 Month",
    description: "Special TouchStone package.",
    status: "active",
  },
  {
    id: "8",
    name: "Taxi Guys",
    price: 1500,
    duration: "1 Month",
    description: "Special package for taxi drivers.",
    status: "active",
  },
  {
    id: "9",
    name: "CustomPackage",
    price: 3000,
    duration: "1 Month",
    description: "Custom corporate package.",
    status: "active",
  },
];

export const dummyTrainers: Trainer[] = [
  {
    id: "1",
    name: "Hamza Malik",
    cnic: "42101-1111111-1",
    gender: "male",
    phone: "0300-5556667",
    specialization: "Bodybuilding",
    joinDate: "2022-12-01",
    status: "active",
  },
  {
    id: "2",
    name: "Usman Ghani",
    cnic: "42101-2222222-2",
    gender: "male",
    phone: "0321-8889990",
    specialization: "Yoga & Cardio",
    joinDate: "2023-03-15",
    status: "active",
  },
  {
    id: "3",
    name: "Bilal Ahmed",
    cnic: "42101-3333333-3",
    gender: "male",
    phone: "0311-2223334",
    specialization: "Crossfit",
    joinDate: "2023-10-10",
    status: "inactive",
  },
];

export const dummyEmployees: Employee[] = [
  {
    id: "1",
    name: "Zeeshan Khan",
    cnic: "42101-1234567-1",
    gender: "male",
    phone: "0300-1112223",
    role: "Receptionist",
    joinDate: "2023-05-10",
    status: "active",
  },
  {
    id: "2",
    name: "Ali Raza",
    cnic: "42101-7654321-2",
    gender: "male",
    phone: "0321-4445556",
    role: "Cleaner",
    joinDate: "2023-08-20",
    status: "active",
  },
  {
    id: "3",
    name: "Maira Ahmed",
    cnic: "42101-9876543-3",
    gender: "female",
    phone: "0311-7778889",
    role: "Accountant",
    joinDate: "2024-01-05",
    status: "inactive",
  },
];

export const dashboardChartData = [
  { name: "Members", value: 1284, color: "#2563eb" },
  { name: "Employees", value: 24, color: "#10b981" },
  { name: "Trainers", value: 12, color: "#f59e0b" },
];
